<#
.SYNOPSIS
  Build and flash esp32/rover_coordinator (Waveshare front and/or rear).

.PARAMETER Board
  front | rear | both. Selects PlatformIO env and devices.json IP.

.PARAMETER Port
  USB COM port (e.g. COM11). Ignored with -Ota.

.PARAMETER Ota
  Use espota over WiFi. IP from -OtaHost or devices.json.

.PARAMETER OtaHost
  Override device IP for OTA (else devices.json for -Board).

.PARAMETER Monitor
  Open serial monitor after USB flash (single board only).
#>
param(
  [ValidateSet("front", "rear", "both")]
  [string] $Board = "front",
  [string] $Port = "COM9",
  [switch] $Ota,
  [string] $OtaHost = "",
  [switch] $Monitor
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$proj = Join-Path $root "esp32\rover_coordinator"
$secrets = Join-Path $proj "include\wifi_secrets.h"
$includeDir = Join-Path $proj "include"
$devicesPath = Join-Path $proj "devices.json"

if (-not (Get-Command pio -ErrorAction SilentlyContinue)) {
  throw "pio (PlatformIO) not found in PATH"
}

New-Item -ItemType Directory -Force -Path $includeDir | Out-Null

$ssid = [string]$env:SOARM_WIFI_SSID
$pass = [string]$env:SOARM_WIFI_PASS
if ([string]::IsNullOrEmpty($ssid)) {
  Write-Warning "SOARM_WIFI_SSID unset - OTA WiFi join disabled in this build"
  $ssid = ""
}
if ([string]::IsNullOrEmpty($pass)) {
  $pass = ""
}

function Escape-CString([string] $value) {
  if ($null -eq $value) { return "" }
  return (($value -replace '\\', '\\') -replace '"', '\"')
}

function Read-DeviceIp([string] $role) {
  if (-not (Test-Path $devicesPath)) { return "" }
  $json = Get-Content -Raw -Path $devicesPath | ConvertFrom-Json
  $prop = $json.PSObject.Properties[$role]
  if ($null -eq $prop) { return "" }
  return [string]$prop.Value
}

function Write-WifiSecrets {
  $ssidC = Escape-CString $ssid
  $passC = Escape-CString $pass
  $secretsBody = @(
    "#pragma once"
    "// Generated by tools/flash_esp_coordinator.ps1 - do not commit."
    "#define WIFI_SSID `"$ssidC`""
    "#define WIFI_PASS `"$passC`""
  ) -join "`n"
  [System.IO.File]::WriteAllText($secrets, $secretsBody + "`n")
}

function Flash-OneBoard([string] $role) {
  $usbEnv = "waveshare_$role"
  $otaEnv = "waveshare_${role}_ota"
  Write-Host "==> Building rover_coordinator (env $usbEnv) [$role]"
  & pio run -e $usbEnv
  if ($LASTEXITCODE -ne 0) { throw "build failed ($role)" }

  if ($Ota) {
    $hostIp = $OtaHost
    if ([string]::IsNullOrEmpty($hostIp)) {
      $hostIp = Read-DeviceIp $role
    }
    if ([string]::IsNullOrEmpty($hostIp)) {
      throw "OTA ${role}: set devices.json.${role} or pass -OtaHost <ip>"
    }
    Write-Host "==> OTA upload to $hostIp (env $otaEnv)"
    & pio run -e $otaEnv -t upload --upload-port $hostIp
  }
  else {
    Write-Host "==> USB upload to $Port (env $usbEnv) - hold Download+Reset if connect fails"
    & pio run -e $usbEnv -t upload --upload-port $Port
  }
  if ($LASTEXITCODE -ne 0) { throw "upload failed ($role)" }
  Write-Host "OK flash done [$role]" -ForegroundColor Green
}

Write-WifiSecrets

$roles = @($Board)
if ($Board -eq "both") {
  if (-not $Ota) {
    throw "-Board both requires -Ota (USB can only target one COM port)"
  }
  if (-not [string]::IsNullOrEmpty($OtaHost)) {
    throw "-OtaHost cannot be used with -Board both (use devices.json IPs)"
  }
  $roles = @("front", "rear")
}

Push-Location $proj
try {
  foreach ($role in $roles) {
    Flash-OneBoard $role
  }
  if ($Monitor -and (-not $Ota) -and ($Board -ne "both")) {
    & pio device monitor --port $Port -b 115200
  }
}
finally {
  Pop-Location
}
