<#
.SYNOPSIS
  Build and flash esp32/rover_coordinator (Waveshare ESP32).

.PARAMETER Port
  USB COM port (e.g. COM9). Ignored with -Ota.

.PARAMETER Ota
  Use espota over WiFi. Requires -OtaHost (device IP).

.PARAMETER OtaHost
  Device IP for OTA (from Serial "wifi: OK ip=..." or WIFI command).

.PARAMETER Monitor
  Open serial monitor after USB flash.
#>
param(
  [string] $Port = "COM9",
  [switch] $Ota,
  [string] $OtaHost = "",
  [switch] $Monitor
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$proj = Join-Path $root "esp32\rover_coordinator"
$secrets = Join-Path $proj "include\wifi_secrets.h"
$includeDir = Join-Path $proj "include"

if (-not (Get-Command pio -ErrorAction SilentlyContinue)) {
  throw "pio (PlatformIO) not found in PATH"
}

New-Item -ItemType Directory -Force -Path $includeDir | Out-Null

$ssid = [string]$env:SOARM_WIFI_SSID
$pass = [string]$env:SOARM_WIFI_PASS
if ([string]::IsNullOrEmpty($ssid)) {
  Write-Warning "SOARM_WIFI_SSID unset - OTA WiFi join disabled in this build"
  $ssid = ""
}
if ([string]::IsNullOrEmpty($pass)) {
  $pass = ""
}

function Escape-CString([string] $value) {
  if ($null -eq $value) { return "" }
  return (($value -replace '\\', '\\') -replace '"', '\"')
}

$ssidC = Escape-CString $ssid
$passC = Escape-CString $pass

$secretsBody = @(
  "#pragma once"
  "// Generated by tools/flash_esp_coordinator.ps1 - do not commit."
  "#define WIFI_SSID `"$ssidC`""
  "#define WIFI_PASS `"$passC`""
) -join "`n"
[System.IO.File]::WriteAllText($secrets, $secretsBody + "`n")

Push-Location $proj
try {
  Write-Host "==> Building rover_coordinator (env waveshare_esp32)"
  & pio run -e waveshare_esp32
  if ($LASTEXITCODE -ne 0) { throw "build failed" }

  if ($Ota) {
    if ([string]::IsNullOrEmpty($OtaHost)) {
      throw "-Ota requires -OtaHost <device-ip>"
    }
    Write-Host "==> OTA upload to $OtaHost (env waveshare_esp32_ota)"
    & pio run -e waveshare_esp32_ota -t upload --upload-port $OtaHost
  }
  else {
    Write-Host "==> USB upload to $Port (hold Download+Reset on Waveshare if connect fails)"
    & pio run -e waveshare_esp32 -t upload --upload-port $Port
  }
  if ($LASTEXITCODE -ne 0) { throw "upload failed" }

  Write-Host "OK flash done" -ForegroundColor Green
  if ($Monitor -and -not $Ota) {
    & pio device monitor --port $Port -b 115200
  }
}
finally {
  Pop-Location
}
